---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml

- name: install chromium-headless
  ansible.builtin.package:
    name: "{{ chromium_headless_packages }}"
    state: present

- name: debian
  when:
    ansible_os_family | lower == 'debian'
  block:
    - name: get LATEST_RELEASE of chromedriver
      ansible.builtin.uri:
        url: https://chromedriver.storage.googleapis.com/LATEST_RELEASE
        method: GET
        return_content: true
      register: chromedriver_version

    - name: download chrome
      ansible.builtin.get_url:
        url: "https://chromedriver.storage.googleapis.com/{{ chromedriver_version.content }}/chromedriver_linux64.zip"
        dest: /tmp/chromedriver_linux64.zip
        mode: 0660
      register: download_archive
      until: download_archive is succeeded
      retries: 5
      delay: 2

    - name: unarchive chromedriver
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/chromedriver_linux64.zip
        dest: /usr/bin/

- name: insert custom profile script to define PATH variables
  ansible.builtin.template:
    src: profile.d/chromedriver.sh.j2
    dest: /etc/profile.d/chromedriver.sh
    owner: root
    group: root
    mode: 0755
