---
name: CI

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:
  workflow_run:
    workflows:
      - "code linter"
    branches:
      - main
      - feature/**
      - fix/**
    types:
      - completed

defaults:
  run:
    working-directory: 'ansible-chromium-headless'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'ansible-chromium-headless'

      - name: set up python.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install dependencies.
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools
          sudo pip3 install ansible==2.10.6 ansible-lint==5.0.0 yamllint==1.26.0 flake8==3.8.4 PyYAML==5.3.1

      - name: YAMLlint
        run: |
          yamllint --version
          yamllint .
      - name: ansible-lint
        run: |
          ansible-lint --version
          ansible-lint .
      - name: flake8
        run: |
          flake8 --version
          flake8 .

  debian:
    name: "${{ matrix.image }} / ansible: ${{ matrix.ansible-version }}"
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:10
          - debian:11
        ansible-version:
          - '5.1'
          - '6.1'
        scenario:
          - default

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-chromium-headless'

      - name: 🐍 set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: test with tox
        run: |
          tox -e ansible_$(printf "${{ matrix.ansible-version }}") \
            -- molecule test --scenario-name default
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}

  ubuntu:
    name: "${{ matrix.image }} / ansible: ${{ matrix.ansible-version }}"
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu:20.04
          - ubuntu:22.04
        ansible-version:
          - '5.1'
          - '6.1'
        scenario:
          - default

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-chromium-headless'

      - name: 🐍 set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: test with tox
        run: |
          tox -e ansible_$(printf "${{ matrix.ansible-version }}") \
            -- molecule test --scenario-name default
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}
